-- AlterTable
ALTER TABLE `Transaction` MODIFY `category` ENUM('COMIDA', 'TRANSPORTE', 'LAZER', 'SAUDE', 'EDUCACAO', 'MORADIA', 'OUTROS', 'INVESTIMENTO', 'SALARIO', 'ASSINATURAS', 'COMBUSTIVEL') NOT NULL;
